version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: curotec_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - curotec_network

  # Redis para cache (opcional - bônus)
  # redis:
  #   image: redis:7-alpine
  #   container_name: curotec_redis
  #   restart: unless-stopped
  #   ports:
  #     - "6380:6379"
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - curotec_network

volumes:
  postgres_data:
    driver: local
  # redis_data:
  #   driver: local

networks:
  curotec_network:
    driver: bridge
