[phases.setup]
nixPkgs = ["nodejs_20", "postgresql_15"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build", "npm run prisma:generate"]

[start]
cmd = "npm start"

[postdeploy]
cmd = "./scripts/postdeploy.sh"

[variables]
NODE_ENV = "production"
