[phases.setup]
nixPkgs = ["nodejs_20", "postgresql_15"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build", "npm run prisma:generate"]

[start]
cmd = "chmod +x scripts/check-env.sh && ./scripts/check-env.sh && npm run prisma:migrate && npm run prisma:seed && npm start"

[variables]
NODE_ENV = "production"
