name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run tests
        working-directory: ./backend
        run: npm test

      - name: Build application
        working-directory: ./backend
        run: npm run build

  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run tests
        working-directory: ./frontend
        run: npm run test:run

      - name: Run linting
        working-directory: ./frontend
        run: npm run lint

      - name: Build application
        working-directory: ./frontend
        run: npm run build

  deploy-notification:
    name: Deploy Notification
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: [test-backend, test-frontend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Reminder
        run: |
          echo "🚀 Tests passed! Ready for deployment."
          echo ""
          echo "📋 Next steps for Railway deployment:"
          echo "1. Go to Railway Dashboard"
          echo "2. Deploy backend service (Root Directory: backend)"
          echo "3. Deploy frontend service (Root Directory: frontend)"
          echo "4. Configure environment variables"
          echo "5. Run database migrations"
          echo ""
          echo "📚 See RAILWAY_DEPLOY.md for detailed instructions"
          echo "🔧 Or use: ./scripts/deploy.sh all"
